#This file was originally generated by PyScripter's unitest wizard

import Testing.referencedatabase as RDB
import unittest
import QualityCheck.CompressTools as CT

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testopenFile(self):
        for fileName in RDB.COMPRESSSAMPLE_DATAFILES:
            r = CT.openFile(fileName)
            self.assertNotEqual(r, None, "Neuspecne dekomprimovany soubor " + fileName)
        pass

def main():
    t = TestGlobalFunctions()
    t.testopenFile()
    unittest.main()

if __name__ == '__main__':
    unittest.main()
